### ISSUE TITLE
'I'm feeling lucky mix' mouseover

### ISSUE THREAD

**Issue by HotelCalifornia** [chrisxclash/play-midnight-firefox#3]
I set the theme to be 'rusty spoon,' and noticed that mousing over the 'I'm feeling lucky mix' box shows the default colours.

Does that make sense? Here are some pictures:

With theme applied:
![before](http://puu.sh/gW3Pp/eb9cca45fe.png)

When mousing over (with theme applied):
![after](http://puu.sh/gW40W/1f11a5aa52.png)

**Comment by ducky** [comment]
Ah okay, thanks for letting me know. The Firefox version takes me longer to get changes updated because they have a stricter process for Plugins.

I'm looking at redoing a lot of the images so I'll add that to my list. Thanks!
