### ISSUE TITLE
Update Firefox version for redesign

### ISSUE THREAD

**Issue by wldcordeiro** [chrisxclash/play-midnight-firefox#4]
I saw that the Chrome version of the plugin was updated to account for the recent redesign whereas the Firefox one has not been. Could we get that remedied?

**Comment by ducky** [comment]
It's currently still in the works right now. Firefox wasn't playing well with the injected Polymer components I was using, so I've got to work on that when I have more time right now.

A temp fix for Firefox is using the Stylish version of the plugin here: https://userstyles.org/styles/115630/play-midnight-for-google-play-music

Apologies it's taken a bit.

**Comment by wldcordeiro** [comment]
@chrisxclash I think you may also need to inject the polyfill for Polymer components because by default they use web components which are hidden behind an about:config preference on Firefox currently.

**Comment by ducky** [comment]
@wldcordeiro That definitely makes sense, I'll look into it. The only problem I'm seeing is that the page already uses Polymer components by default, so I'm assuming the polyfill would already be there. I feel like it has something to do with me injecting them after the fact and it not compiling them properly, but I could be totally wrong.
